# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Verilog/ImageProcessingofSketch/ImageProcessing.cache/wt [current_project]
set_property parent.project_path D:/Verilog/ImageProcessingofSketch/ImageProcessing.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  d:/Verilog/ImageProcessingofSketch/ImageProcessing.srcs/sources_1
  d:Xilinx/vivado-library-master
} [current_project]
add_files -quiet d:/Verilog/ImageProcessingofSketch/ImageProcessing.srcs/sources_1/ip/outputBuffer/outputBuffer.dcp
set_property used_in_implementation false [get_files d:/Verilog/ImageProcessingofSketch/ImageProcessing.srcs/sources_1/ip/outputBuffer/outputBuffer.dcp]
read_verilog -library xil_defaultlib {
  D:/Verilog/ImageProcessingofSketch/ImageProcessing.srcs/sources_1/new/LineBuffer.v
  D:/Verilog/ImageProcessingofSketch/ImageProcessing.srcs/sources_1/new/conv1.v
  D:/Verilog/ImageProcessingofSketch/ImageProcessing.srcs/sources_1/imports/new/imageControl.v
  D:/Verilog/ImageProcessingofSketch/ImageProcessing.srcs/sources_1/new/imageProcessTop.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top imageProcessTop -part xc7z020clg484-1


write_checkpoint -force -noxdef imageProcessTop.dcp

catch { report_utilization -file imageProcessTop_utilization_synth.rpt -pb imageProcessTop_utilization_synth.pb }
